// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: pb/hello.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// 服务端流式RPC
	ServerStreamSayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (Hello_ServerStreamSayHelloClient, error)
	// 客户端流式RPC
	ClientStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Hello_ClientStreamSayHelloClient, error)
	// 双向流式RPC
	BudiSayHello(ctx context.Context, opts ...grpc.CallOption) (Hello_BudiSayHelloClient, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) ServerStreamSayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (Hello_ServerStreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[0], "/hello/ServerStreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServerStreamSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Hello_ServerStreamSayHelloClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type helloServerStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *helloServerStreamSayHelloClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloClient) ClientStreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Hello_ClientStreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[1], "/hello/ClientStreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloClientStreamSayHelloClient{stream}
	return x, nil
}

type Hello_ClientStreamSayHelloClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type helloClientStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *helloClientStreamSayHelloClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloClientStreamSayHelloClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloClient) BudiSayHello(ctx context.Context, opts ...grpc.CallOption) (Hello_BudiSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[2], "/hello/BudiSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloBudiSayHelloClient{stream}
	return x, nil
}

type Hello_BudiSayHelloClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type helloBudiSayHelloClient struct {
	grpc.ClientStream
}

func (x *helloBudiSayHelloClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloBudiSayHelloClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServer is the server API for Hello service.
// All implementations must embed UnimplementedHelloServer
// for forward compatibility
type HelloServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	// 服务端流式RPC
	ServerStreamSayHello(*Request, Hello_ServerStreamSayHelloServer) error
	// 客户端流式RPC
	ClientStreamSayHello(Hello_ClientStreamSayHelloServer) error
	// 双向流式RPC
	BudiSayHello(Hello_BudiSayHelloServer) error
	mustEmbedUnimplementedHelloServer()
}

// UnimplementedHelloServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (UnimplementedHelloServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloServer) ServerStreamSayHello(*Request, Hello_ServerStreamSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamSayHello not implemented")
}
func (UnimplementedHelloServer) ClientStreamSayHello(Hello_ClientStreamSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamSayHello not implemented")
}
func (UnimplementedHelloServer) BudiSayHello(Hello_BudiSayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method BudiSayHello not implemented")
}
func (UnimplementedHelloServer) mustEmbedUnimplementedHelloServer() {}

// UnsafeHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServer will
// result in compilation errors.
type UnsafeHelloServer interface {
	mustEmbedUnimplementedHelloServer()
}

func RegisterHelloServer(s grpc.ServiceRegistrar, srv HelloServer) {
	s.RegisterService(&Hello_ServiceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_ServerStreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServer).ServerStreamSayHello(m, &helloServerStreamSayHelloServer{stream})
}

type Hello_ServerStreamSayHelloServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type helloServerStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *helloServerStreamSayHelloServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Hello_ClientStreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).ClientStreamSayHello(&helloClientStreamSayHelloServer{stream})
}

type Hello_ClientStreamSayHelloServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type helloClientStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *helloClientStreamSayHelloServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloClientStreamSayHelloServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Hello_BudiSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).BudiSayHello(&helloBudiSayHelloServer{stream})
}

type Hello_BudiSayHelloServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type helloBudiSayHelloServer struct {
	grpc.ServerStream
}

func (x *helloBudiSayHelloServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloBudiSayHelloServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Hello_ServiceDesc is the grpc.ServiceDesc for Hello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamSayHello",
			Handler:       _Hello_ServerStreamSayHello_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamSayHello",
			Handler:       _Hello_ClientStreamSayHello_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BudiSayHello",
			Handler:       _Hello_BudiSayHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/hello.proto",
}
